### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Aspie96** [leopiney/deep-forest#12]
Hi.

Is there any plans to license this project?

**Comment by leopiney** [comment]
Hey sorry I didn’t answer you quickly. I didn’t plant to add a license haha but feel free to use any of this code. Also, there’s an official implementation of this that took some months for the writers of the paper to publish, but you can find it [here](https://github.com/kingfengji/gcForest/)

Good luck 👍

**Comment by Aspie96** [comment]
The official implementation also has no license XD

> feel free to use any of this code
If you want people to be allowed to I suggest you adding a license, because it's much clearer (without it's "all rights reserved").

If you don't want to place any restrictions you can use MIT, which requires attribution (or you can use Unlicense or WTFPL if you don't care).

Thank you for the reply!

**Comment by leopiney** [comment]
There you have it now, I hope that’s helpful 👍
