### ISSUE TITLE
Why the `min_samples_split` is 21 in mgs?

### ISSUE THREAD

**Issue by inkzk** [leopiney/deep-forest#3]
Shouldn't it be 11?

**Comment by XiaolongJason** [comment]
Forest in multi_grsained scanning:Tree growth: till pure leaf or <= 20 instances
Forest in cascade: Tree growth: till pure leaf or <= 10 instances

**Comment by leopiney** [comment]
Hi @zhaokai410 sorry I've been inactive these last months.

Thank you @XiaolongJason very much for the answer!
